FROM python:3.10-slim

WORKDIR /app

# Install dependencies directly
RUN pip install --no-cache-dir Flask==2.2.3 flask-cors==3.0.10 pymongo==4.3.3 python-dotenv==1.0.0 beautifulsoup4==4.11.2 requests==2.28.2 dnspython==2.3.0 gunicorn==20.1.0

# Copy the application
COPY . .

# Set environment variable for Flask
ENV PORT=8080

# Command to run
CMD ["python", "app.py"]