name: End-to-End Tests

# When to run this workflow
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  cypress-tests:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest
    
    services:
      # MongoDB service container for backend tests
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
    
    steps:
      # Check out repository code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up Python for backend
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      # Install backend dependencies
      - name: Install Python dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      
      # Set up Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: home-search-frontend/package-lock.json
      
      # Install frontend dependencies
      - name: Install Node.js dependencies
        run: |
          cd home-search-frontend
          npm ci
      
      # Start backend server
      - name: Start backend server
        run: |
          cd backend
          python app.py &
          echo "Backend server started"
          sleep 5  # Wait for server to start
        env:
          MONGO_DB_USERNAME: test
          MONGO_DB_PASSWORD: test
          MONGO_DB_CLUSTER_URL: localhost:27017
          MONGO_DB_NAME: property_test_db
      
      # Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: home-search-frontend
          start: npm start
          wait-on: 'http://localhost:3000, http://127.0.0.1:5000/api/properties'
          wait-on-timeout: 120
      
      # Upload screenshots and videos
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: home-search-frontend/cypress/screenshots
      
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: home-search-frontend/cypress/videos